language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps="no"

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.3
      env: deps="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" != "low" ]; then composer install; fi
  - composer require --dev satooshi/php-coveralls:~0.6

script: phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success: |
    if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;
